In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [15]:
books = pd.read_csv(r'G:\Robotronix\Projects\Book_recommender_system\dataset\books.csv')
users = pd.read_csv(r'G:\Robotronix\Projects\Book_recommender_system\dataset\users.csv')
ratings = pd.read_csv(r'G:\Robotronix\Projects\Book_recommender_system\dataset\ratings.csv')

In [3]:
books.isna().any()

ISBN                   False
Book-Title             False
Book-Author             True
Year-Of-Publication    False
Publisher               True
Image-URL-S            False
Image-URL-M            False
Image-URL-L             True
dtype: bool

In [4]:
books.isna().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [5]:
ratings.isna().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [6]:
users.isna().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [7]:
books.duplicated().sum()

0

In [8]:
ratings.duplicated().sum()

0

In [9]:
users.duplicated().sum()

0

In [10]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [23]:
books['Book-Title'] = books['Book-Title'].apply(lambda name : name.lower())

popularity based recommendation system means highest or threshold average ratings books should be shown to users

In [11]:
# merge_df_rating_book

In [24]:
merge_df_rating_book = ratings.merge(books, on='ISBN')

In [25]:
rating_count_df = merge_df_rating_book.groupby('Book-Title')['Book-Rating'].count().reset_index()

In [26]:
rating_count_df = rating_count_df.rename(columns={'Book-Rating':'rating_count'})
rating_count_df

                                               Book-Title  rating_count
0        a light in the storm: the civil war diary of ...             4
1                                   always have popsicles             1
2                    apple magic (the collector's series)             1
3        ask lily (young women of faith: lily series, ...             1
4        beyond ibm: leadership marketing and finance ...             1
...                                                   ...           ...
237907                                      ã?â?lpiraten.             2
237908                     ã?â?rger mit produkt x. roman.             4
237909                                ã?â?sterlich leben.             1
237910                              ã?â?stlich der berge.             3
237911                                  ã?â?thique en toc             2

[237912 rows x 2 columns]

In [27]:
max(rating_count_df['rating_count'])

2502

In [28]:
rating_count_df[rating_count_df['rating_count'] == 2502]

         Book-Title  rating_count
232037  wild animus          2502

In [29]:
avg_rating_df = merge_df_rating_book.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df = avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'})
avg_rating_df

                                               Book-Title  avg_ratings
0        a light in the storm: the civil war diary of ...     2.250000
1                                   always have popsicles     0.000000
2                    apple magic (the collector's series)     0.000000
3        ask lily (young women of faith: lily series, ...     8.000000
4        beyond ibm: leadership marketing and finance ...     0.000000
...                                                   ...          ...
237907                                      ã?â?lpiraten.     0.000000
237908                     ã?â?rger mit produkt x. roman.     5.250000
237909                                ã?â?sterlich leben.     7.000000
237910                              ã?â?stlich der berge.     2.666667
237911                                  ã?â?thique en toc     4.000000

[237912 rows x 2 columns]

In [30]:
popular_books_df = rating_count_df.merge(avg_rating_df,on='Book-Title')
popular_books_df

,Book-Title,rating_count,avg_ratings
0,a light in the storm: the civil war diary of ...,4,2.250000
1,always have popsicles,1,0.000000
2,apple magic (the collector's series),1,0.000000
3,"ask lily (young women of faith: lily series, ...",1,8.000000
4,beyond ibm: leadership marketing and finance ...,1,0.000000
...,...,...,...
237907,ã?â?lpiraten.,2,0.000000
237908,ã?â?rger mit produkt x. roman.,4,5.250000
237909,ã?â?sterlich leben.,1,7.000000
237910,ã?â?stlich der berge.,3,2.666667
237911,ã?â?thique en toc,2,4.000000

In [31]:
popular_books_df = popular_books_df[popular_books_df.rating_count>=250]

In [32]:
popular_books_df = popular_books_df.sort_values(by='avg_ratings',ascending=False)

In [33]:
popular_books_df = popular_books_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','rating_count','avg_ratings']]

In [34]:
popular_books_df

,Book-Title,Book-Author,Image-URL-M,rating_count,avg_ratings
0,harry potter and the prisoner of azkaban (book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,harry potter and the goblet of fire (book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,harry potter and the sorcerer's stone (book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,harry potter and the order of the phoenix (boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,harry potter and the chamber of secrets (book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
...,...,...,...,...,...
753,vinegar hill (oprah's book club (paperback)),A. Manette Ansay,http://images.amazon.com/images/P/0380730138.0...,265,2.245283
754,whispers,BELVA PLAIN,http://images.amazon.com/images/P/0440216745.0...,286,2.199301
764,presumed innocent,Scott Turow,http://images.amazon.com/images/P/0446359866.0...,296,2.125000
771,isle of dogs,Patricia Cornwell,http://images.amazon.com/images/P/0425182908.0...,288,2.000000
777,wild animus,Rich Shapero,http://images.amazon.com/images/P/0971880107.0...,2502,1.019584

In [35]:
merge_df_rating_book['User-ID']

0          276725
1            2313
2            6543
3            8680
4           10314
            ...
1031131    276688
1031132    276688
1031133    276690
1031134    276704
1031135    276704
Name: User-ID, Length: 1031136, dtype: int64

In [36]:
merge_df_rating_book.groupby('User-ID')['Book-Title'].count() > 200

User-ID
2         False
8         False
9         False
10        False
12        False
          ...
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Title, Length: 92106, dtype: bool

In [37]:
temp = merge_df_rating_book.groupby('User-ID')['Book-Title'].count() >200  # that users who rated minimum 200 books
required_users = temp[temp].index
required_users

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [38]:
filtered_rating_by_users = merge_df_rating_book[merge_df_rating_book['User-ID'].isin(required_users)]
filtered_rating_by_users

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,flesh tones: a novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,flesh tones: a novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,flesh tones: a novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,flesh tones: a novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,flesh tones: a novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,the theology of the hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,the ordeal of integration: progress and resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,pushcart's complete rotten reviews &amp; rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,there's a porcupine in my outhouse: misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,die biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [39]:
temp = filtered_rating_by_users.groupby('Book-Title')['Book-Rating'].count() >= 50 # those books for which user ratings are greater than 50
famous_books = temp[temp].index
famous_books

Index(['1984', '1st to die: a novel', '2nd chance', '4 blondes',
       '\o\" is for outlaw"', 'a bend in the road', 'a case of need',
       'a child called \it\": one child's courage to survive"',
       'a civil action', 'a cry in the night',
       ...
       'winter solstice', 'wish you well', 'without remorse',
       'wizard and glass (the dark tower, book 4)', 'wld accordng garp',
       'wuthering heights', 'year of wonders', 'you belong to me',
       'zen and the art of motorcycle maintenance: an inquiry into values',
       'zoya'],
      dtype='object', name='Book-Title', length=718)

In [40]:
temp

Book-Title
 a light in the storm: the civil war diary of amelia martin, fenwick island, delaware, 1861 (dear america)    False
 always have popsicles                                                                                        False
 apple magic (the collector's series)                                                                         False
 beyond ibm: leadership marketing and finance for the 1990s                                                   False
 clifford visita el hospital (clifford el gran perro colorado)                                                False
                                                                                                              ...
ã?â?ber das fernsehen.                                                                                        False
ã?â?ber die pflicht zum ungehorsam gegen den staat.                                                           False
ã?â?lpiraten.                                                                                                 False
ã?â?stlich der berge.                                                                                         False
ã?â?thique en toc                                                                                             False
Name: Book-Rating, Length: 154076, dtype: bool

In [41]:
final_ratings = filtered_rating_by_users[filtered_rating_by_users['Book-Title'].isin(famous_books)]

In [42]:
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,the notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,the notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,the notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,the notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,the notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,the catcher in the rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,the rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,me talk pretty one day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [43]:
pivot_df = final_ratings.pivot_table(index='Book-Title', columns= 'User-ID', values= 'Book-Rating') # indexes are books and columns are user ids
pivot_df

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to die: a novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\o\"" is for outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wuthering heights,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
year of wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
you belong to me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN
zen and the art of motorcycle maintenance: an inquiry into values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
pivot_df = pivot_df.fillna(0)
pivot_df

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to die: a novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\o\"" is for outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wuthering heights,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
year of wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
you belong to me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
zen and the art of motorcycle maintenance: an inquiry into values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
pivot_df.loc['1984']

User-ID
254       9.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ...
274308    0.0
275970    0.0
277427    0.0
277639    0.0
278418    0.0
Name: 1984, Length: 810, dtype: float64

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
cosine_similarity_score = cosine_similarity(pivot_df)

In [49]:
cosine_similarity_score[0]

array([1.        , 0.10255025, 0.01220856, 0.        , 0.04316046,
       0.05367224, 0.02774901, 0.08216491, 0.13732869, 0.        ,
       0.03261686, 0.03667591, 0.02322418, 0.06766487, 0.02083978,
       0.09673735, 0.08303112, 0.13388865, 0.11153543, 0.05100411,
       0.02517784, 0.11706383, 0.        , 0.14333793, 0.07847534,
       0.06150451, 0.08723968, 0.        , 0.0987527 , 0.07600328,
       0.00751764, 0.01473221, 0.        , 0.07965814, 0.04522617,
       0.01525489, 0.09495938, 0.0182307 , 0.02610465, 0.07984012,
       0.12343843, 0.12167134, 0.0569124 , 0.08354155, 0.07886098,
       0.08785938, 0.05491435, 0.0548505 , 0.27026514, 0.09779123,
       0.06016046, 0.08958835, 0.06748675, 0.        , 0.04468098,
       0.01920872, 0.        , 0.05629067, 0.00557964, 0.07877059,
       0.05219479, 0.18908177, 0.        , 0.01240656, 0.02848981,
       0.04279502, 0.12680125, 0.16566735, 0.        , 0.13357242,
       0.06615478, 0.        , 0.        , 0.        , 0.04521795,
       0.10968075, 0.02806606, 0.02613277, 0.06876131, 0.01331627,
       0.10519138, 0.03349457, 0.01363458, 0.23669374, 0.        ,
       0.10397941, 0.06167753, 0.14176273, 0.11661083, 0.08331012,
       0.00850895, 0.06609943, 0.15850821, 0.0328052 , 0.01068915,
       0.02579782, 0.02114859, 0.11623381, 0.02687779, 0.02175821,
       0.        , 0.01601663, 0.12114266, 0.04768603, 0.05819184,
       0.06510722, 0.        , 0.0476705 , 0.05273165, 0.0281001 ,
       0.06524573, 0.02116345, 0.02097868, 0.07422249, 0.01752778,
       0.03734567, 0.        , 0.01579666, 0.11039448, 0.16527277,
       0.14540673, 0.06237454, 0.08139489, 0.05655414, 0.07458203,
       0.03771888, 0.0593633 , 0.02955369, 0.03355603, 0.04734093,
       0.01006643, 0.01671982, 0.07258935, 0.        , 0.        ,
       0.        , 0.02213731, 0.03067819, 0.0997498 , 0.        ,
       0.01617258, 0.02410862, 0.0281084 , 0.        , 0.        ,
       0.01812877, 0.02880827, 0.        , 0.05995157, 0.02127671,
       0.1034119 , 0.02766748, 0.10684795, 0.09898722, 0.14145186,
       0.05007429, 0.09428289, 0.01411249, 0.        , 0.07835976,
       0.00882242, 0.04515898, 0.        , 0.01281412, 0.04003334,
       0.07477661, 0.01217906, 0.01887393, 0.02667484, 0.01432864,
       0.14702847, 0.06087282, 0.02578321, 0.02741876, 0.        ,
       0.14909595, 0.05606788, 0.        , 0.03199916, 0.03643817,
       0.01962921, 0.22222254, 0.01515845, 0.09673268, 0.02190023,
       0.02013549, 0.05400331, 0.07262017, 0.01111637, 0.03649872,
       0.05994664, 0.        , 0.14691167, 0.02086005, 0.10359635,
       0.09794375, 0.06609997, 0.12871083, 0.07534189, 0.01147457,
       0.        , 0.02460165, 0.        , 0.18049207, 0.05141892,
       0.0477174 , 0.10312712, 0.13278139, 0.04577414, 0.05372984,
       0.034785  , 0.        , 0.09203039, 0.08948037, 0.06388401,
       0.04773328, 0.15570975, 0.08671331, 0.12338217, 0.03852677,
       0.03965393, 0.08137649, 0.0878469 , 0.12177532, 0.02433703,
       0.00272862, 0.        , 0.        , 0.03671505, 0.15280984,
       0.0370943 , 0.07458136, 0.09746697, 0.05416091, 0.10266993,
       0.07574414, 0.06426526, 0.01822893, 0.01559752, 0.02033559,
       0.02463593, 0.00962099, 0.02135369, 0.0190337 , 0.06806265,
       0.02032116, 0.11784706, 0.07839488, 0.08422558, 0.        ,
       0.02040796, 0.        , 0.04698246, 0.08294513, 0.13974514,
       0.01234525, 0.13510608, 0.07423489, 0.11841889, 0.04930091,
       0.01621668, 0.02633023, 0.04815972, 0.01870984, 0.10174253,
       0.13257638, 0.        , 0.0551027 , 0.0186115 , 0.        ,
       0.04504598, 0.03482459, 0.15793754, 0.06795353, 0.08466191,
       0.02987653, 0.        , 0.        , 0.08781993, 0.07885279,
       0.04799058, 0.0133104 , 0.02123837, 0.04549923, 0.08673969,
       0.00885998, 0.01374687, 0.02022145, 0.02414122, 0.12548312,
       0.        , 0.02482518, 0.06520606, 0.        , 0.0606983 ,
       0.01177824, 0.13974105, 0.01978844, 0.01260824, 0.07196908,
       0.04433883, 0.02943085, 0.02242496, 0.06541868, 0.07319111,
       0.14281399, 0.01579507, 0.11979305, 0.01858409, 0.13445377,
       0.04809338, 0.09790644, 0.        , 0.06465119, 0.        ,
       0.17415731, 0.07437756, 0.        , 0.0786772 , 0.12389065,
       0.01042391, 0.02580849, 0.        , 0.0895139 , 0.04005551,
       0.19182231, 0.02267512, 0.01730347, 0.03054044, 0.07008822,
       0.10084626, 0.10467615, 0.01683462, 0.11942651, 0.10266459,
       0.03549836, 0.02667484, 0.07652765, 0.08474056, 0.01831977,
       0.        , 0.02177482, 0.15293362, 0.04390554, 0.        ,
       0.01063251, 0.02153089, 0.02946443, 0.        , 0.02076783,
       0.        , 0.01194825, 0.00953675, 0.2067554 , 0.01554292,
       0.0390266 , 0.06681046, 0.09014973, 0.05914735, 0.06206857,
       0.        , 0.02005959, 0.07843566, 0.16337845, 0.07161075,
       0.        , 0.14595258, 0.07561631, 0.02939738, 0.04779629,
       0.01807238, 0.11362722, 0.07999693, 0.08912337, 0.11934868,
       0.09791273, 0.10941777, 0.        , 0.02115842, 0.0600393 ,
       0.01797154, 0.05755408, 0.02162138, 0.09754449, 0.13107652,
       0.        , 0.06829904, 0.09132922, 0.03548392, 0.02781406,
       0.01533368, 0.06113179, 0.01757286, 0.02471294, 0.0180158 ,
       0.11789806, 0.06260182, 0.1427861 , 0.        , 0.06671644,
       0.        , 0.        , 0.05762086, 0.02266096, 0.00844876,
       0.02297481, 0.07136276, 0.15305514, 0.08408817, 0.        ,
       0.07215496, 0.01545947, 0.10135299, 0.        , 0.01676344,
       0.        , 0.0502188 , 0.16041182, 0.        , 0.02329035,
       0.0198727 , 0.01105674, 0.02548034, 0.00896044, 0.08246122,
       0.01873984, 0.07025003, 0.0216367 , 0.12822982, 0.09998772,
       0.08642895, 0.06355197, 0.02883024, 0.04335826, 0.0470659 ,
       0.05223733, 0.        , 0.08982751, 0.00875634, 0.09923542,
       0.10228551, 0.        , 0.12327577, 0.12307492, 0.01758929,
       0.02028125, 0.1033827 , 0.13028171, 0.08988894, 0.09005001,
       0.05332049, 0.08033436, 0.04597795, 0.06139888, 0.02285694,
       0.02304904, 0.06523041, 0.01915363, 0.        , 0.04542766,
       0.        , 0.        , 0.05261954, 0.01317088, 0.        ,
       0.09028287, 0.        , 0.0485931 , 0.12508514, 0.0734819 ,
       0.10354481, 0.01718807, 0.09919937, 0.08091989, 0.00358835,
       0.02228843, 0.04757132, 0.11122765, 0.05143481, 0.0566614 ,
       0.        , 0.06087719, 0.10800615, 0.        , 0.07554686,
       0.        , 0.13644384, 0.04796763, 0.15842494, 0.        ,
       0.01759864, 0.05438295, 0.        , 0.08100801, 0.13090711,
       0.00581844, 0.07150547, 0.05428487, 0.06143184, 0.05161653,
       0.1951182 , 0.1149488 , 0.06513047, 0.06401961, 0.        ,
       0.        , 0.10853662, 0.11400426, 0.0463925 , 0.01825277,
       0.        , 0.01195201, 0.21057744, 0.05809707, 0.04349156,
       0.02646256, 0.07276403, 0.05264857, 0.07242165, 0.01626564,
       0.06790898, 0.02431809, 0.01313888, 0.13617057, 0.11784149,
       0.08588206, 0.09284352, 0.11277297, 0.06868983, 0.08200947,
       0.13369059, 0.        , 0.19972625, 0.02286207, 0.0806288 ,
       0.        , 0.05756015, 0.06738056, 0.        , 0.19656288,
       0.06306426, 0.03499381, 0.06123119, 0.09596456, 0.02180168,
       0.02317515, 0.06476149, 0.07052241, 0.08280452, 0.1700872 ,
       0.07213921, 0.01172201, 0.08541218, 0.17990898, 0.08007284,
       0.01739625, 0.16728777, 0.26396194, 0.1840891 , 0.05600273,
       0.04133586, 0.06911015, 0.14456847, 0.22626397, 0.19208896,
       0.0239334 , 0.20025064, 0.01507653, 0.05144282, 0.1233368 ,
       0.1420166 , 0.02472079, 0.08563805, 0.02363426, 0.12794024,
       0.01083153, 0.07352436, 0.09532519, 0.03421895, 0.07194212,
       0.02297079, 0.15344079, 0.08856302, 0.        , 0.        ,
       0.01878656, 0.09772942, 0.04404359, 0.15211972, 0.0152225 ,
       0.10307399, 0.05715789, 0.04600056, 0.06303899, 0.06572303,
       0.14421331, 0.08272478, 0.        , 0.04203701, 0.02276077,
       0.17381829, 0.01909967, 0.16000268, 0.14681486, 0.        ,
       0.05940546, 0.07725115, 0.07464763, 0.06546696, 0.07021577,
       0.18921368, 0.02494136, 0.01705027, 0.05437622, 0.04932819,
       0.        , 0.12092483, 0.08001595, 0.12858515, 0.02306658,
       0.06129105, 0.02090769, 0.04504931, 0.1026659 , 0.10725982,
       0.0260534 , 0.00173709, 0.0987294 , 0.08077482, 0.02159226,
       0.01614275, 0.0208464 , 0.09797466, 0.01906731, 0.18571699,
       0.05344577, 0.18925314, 0.05894189, 0.01488161, 0.1202478 ,
       0.09840359, 0.01048126, 0.10596224, 0.07617195, 0.0805439 ,
       0.        , 0.23299389, 0.01073642, 0.13573542, 0.02659974,
       0.14440017, 0.        , 0.12522954, 0.0645501 , 0.02817522,
       0.14445559, 0.01721045, 0.09508161, 0.0517902 , 0.05977497,
       0.18410818, 0.08704224, 0.10990764, 0.10850377, 0.03954865,
       0.0383631 , 0.02463491, 0.07845405, 0.03455548, 0.03007681,
       0.02484076, 0.04223674, 0.14444517, 0.12340234, 0.01510201,
       0.0284437 , 0.02132016, 0.07391778, 0.08904276, 0.15893871,
       0.06947574, 0.01060787, 0.09870926, 0.05711356, 0.09488374,
       0.00948943, 0.13365876, 0.05794064, 0.        , 0.06721284,
       0.02066998, 0.        , 0.01839428, 0.        , 0.12655364,
       0.08418288, 0.09095705, 0.00730589, 0.07453597, 0.        ,
       0.04218803, 0.08392849, 0.07785801, 0.        , 0.07151794,
       0.02407593, 0.01635126, 0.03734567, 0.05237227, 0.01140169,
       0.00968725, 0.12530648, 0.        , 0.00890035, 0.05864096,
       0.01634679, 0.12110367, 0.07347567])

In [51]:
np.where(pivot_df.index == '4 blondes')[0][0]

3

In [52]:
cosine_similarity_score[3]

array([0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.11158235, 0.        , 0.        , 0.        ,
       0.07439555, 0.        , 0.        , 0.14576203, 0.05499338,
       0.        , 0.        , 0.        , 0.        , 0.04289816,
       0.        , 0.11215379, 0.        , 0.        , 0.02473898,
       0.        , 0.0254068 , 0.12305174, 0.        , 0.        ,
       0.09182183, 0.        , 0.06859607, 0.        , 0.0779401 ,
       0.03696943, 0.08134518, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05477141, 0.        ,
       0.05958855, 0.        , 0.        , 0.07684047, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06703391, 0.        , 0.        , 0.03245271, 0.        ,
       0.0408861 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.0094036 , 0.        , 0.        , 0.00939554,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00945087, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.01391526, 0.        , 0.08376125, 0.        ,
       0.        , 0.        , 0.        , 0.13135471, 0.17154711,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04600352, 0.        , 0.05049882, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05043018, 0.        , 0.10676555, 0.05710297, 0.01066106,
       0.        , 0.        , 0.08575255, 0.06960268, 0.00912889,
       0.        , 0.        , 0.05441552, 0.        , 0.03913303,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.01440697, 0.        , 0.        , 0.12004349,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0272477 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.12334016, 0.        , 0.        , 0.00956496,
       0.        , 0.        , 0.03990103, 0.14343389, 0.        ,
       0.        , 0.04560018, 0.06717621, 0.10647205, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.09259924,
       0.06387072, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04320058, 0.        , 0.01905907, 0.07076543,
       0.        , 0.        , 0.00955608, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.12883478, 0.07058596, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06184529, 0.        , 0.        ,
       0.        , 0.        , 0.07890729, 0.        , 0.        ,
       0.        , 0.03151186, 0.09305322, 0.09922711, 0.        ,
       0.06613282, 0.11303598, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00731979, 0.        , 0.08500151, 0.04228386, 0.04304939,
       0.0523528 , 0.        , 0.0824635 , 0.07937953, 0.10513545,
       0.        , 0.        , 0.        , 0.        , 0.1488746 ,
       0.10506086, 0.        , 0.09415231, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03707166,
       0.        , 0.0891433 , 0.        , 0.05545546, 0.        ,
       0.        , 0.        , 0.        , 0.06045644, 0.        ,
       0.0412574 , 0.        , 0.        , 0.04811093, 0.00845878,
       0.        , 0.        , 0.04681232, 0.        , 0.04757652,
       0.        , 0.10491215, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0392045 , 0.        , 0.04991736,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.09514653, 0.02815089, 0.        , 0.        , 0.        ,
       0.        , 0.11887355, 0.        , 0.        , 0.04565633,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.11840184, 0.08608478, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07223486, 0.        , 0.06118933,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.02930631, 0.        , 0.        , 0.        , 0.14284952,
       0.06750414, 0.        , 0.        , 0.        , 0.03625535,
       0.03924103, 0.        , 0.        , 0.        , 0.0118392 ,
       0.        , 0.        , 0.        , 0.        , 0.05619894,
       0.08016503, 0.        , 0.0571244 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08985299, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.17173795, 0.        , 0.13237924,
       0.00934346, 0.        , 0.        , 0.        , 0.29434548,
       0.04385491, 0.        , 0.        , 0.06077196, 0.        ,
       0.09678465, 0.        , 0.03287737, 0.01218133, 0.        ,
       0.        , 0.09655285, 0.        , 0.16052106, 0.        ,
       0.03096698, 0.        , 0.        , 0.        , 0.13583222,
       0.        , 0.10956997, 0.        , 0.        , 0.19281549,
       0.12950201, 0.        , 0.0538561 , 0.        , 0.        ,
       0.        , 0.11529596, 0.13520967, 0.03426987, 0.05833565,
       0.        , 0.        , 0.08270159, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.080029  , 0.        , 0.        , 0.        ,
       0.16089893, 0.        , 0.        , 0.17982397, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07149048,
       0.        , 0.        , 0.        , 0.07343662, 0.012991  ,
       0.        , 0.06441866, 0.        , 0.        , 0.03800051,
       0.        , 0.12113804, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0892645 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.10434075, 0.0186227 ,
       0.        , 0.        , 0.        , 0.04428181, 0.06261255,
       0.        , 0.        , 0.        , 0.04532712, 0.00941595,
       0.03716325, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0438688 , 0.08001838, 0.06395111, 0.        , 0.        ,
       0.        , 0.        , 0.06109947, 0.06033541, 0.        ,
       0.        , 0.13638741, 0.        , 0.1206014 , 0.        ,
       0.        , 0.13903237, 0.0715168 , 0.        , 0.04737058,
       0.07345872, 0.        , 0.05275083, 0.        , 0.        ,
       0.06508571, 0.        , 0.        , 0.13186636, 0.02110099,
       0.        , 0.        , 0.        , 0.02328199, 0.02966354,
       0.        , 0.        , 0.        , 0.14774674, 0.        ,
       0.        , 0.08744402, 0.        , 0.        , 0.        ,
       0.06819965, 0.        , 0.06155462, 0.        , 0.        ,
       0.        , 0.        , 0.00938315, 0.12707201, 0.        ,
       0.        , 0.12726645, 0.        , 0.09144571, 0.04450014,
       0.        , 0.01026363, 0.04124866, 0.        , 0.00868606,
       0.        , 0.        , 0.07261226, 0.        , 0.        ,
       0.21653837, 0.11565017, 0.        , 0.01068115, 0.        ,
       0.0669917 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06533776, 0.        , 0.        ,
       0.07274018, 0.        , 0.06030866, 0.07154773, 0.        ,
       0.        , 0.        , 0.        , 0.15044465, 0.        ,
       0.07894739, 0.02455742, 0.06606221, 0.        , 0.02132214,
       0.        , 0.        , 0.        , 0.06338858, 0.        ,
       0.        , 0.05785883, 0.        , 0.0152785 , 0.        ,
       0.07198303, 0.01012946, 0.02616119, 0.08277692, 0.09782603,
       0.07587245, 0.        , 0.01101878, 0.        , 0.03814519,
       0.        , 0.        , 0.        , 0.02726329, 0.12173922,
       0.04951189, 0.        , 0.        , 0.0699969 , 0.        ,
       0.        , 0.        , 0.09616416, 0.07840325, 0.        ,
       0.        , 0.0943043 , 0.02710462, 0.        , 0.01086701,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06194181, 0.06321971, 0.        , 0.        , 0.        ,
       0.05856949, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07223443, 0.        , 0.        , 0.09678655, 0.        ,
       0.        , 0.06191258, 0.        , 0.        , 0.        ,
       0.0411626 , 0.        , 0.        , 0.05156192, 0.        ,
       0.11258865, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05758506, 0.        , 0.02976597, 0.        ,
       0.12265144, 0.        , 0.03847017, 0.        , 0.        ,
       0.        , 0.        , 0.07726781, 0.        , 0.        ,
       0.06925589, 0.07256944, 0.07672358, 0.        , 0.        ,
       0.        , 0.03348088, 0.04574178, 0.12634133, 0.07134425,
       0.10735806, 0.0211341 , 0.        , 0.        , 0.        ,
       0.        , 0.01194782, 0.        , 0.12078942, 0.10863774,
       0.05282081, 0.        , 0.        ])

In [53]:
x = sorted(list(enumerate(cosine_similarity_score[3])), key=lambda x:x[1], reverse=True)[1:6]

In [54]:
x

[(374, 0.29434547853881865),
 (565, 0.21653836784507968),
 (399, 0.19281549158555333),
 (428, 0.17982397105535214),
 (367, 0.1717379494369234)]

In [55]:
for i in x:
    print(pivot_df.index[i[0]])

one hundred years of solitude
the house of the spirits
pride and prejudice
seabiscuit
notes from a small island

In [56]:
data = []
for i in x:
    item = []
    temp_df = books[books['Book-Title'] == pivot_df.index[i[0]]]
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
    print(item)
    data.append(item)

['one hundred years of solitude', 'Gabriel Garcia Marquez', 'http://images.amazon.com/images/P/0060929790.01.MZZZZZZZ.jpg']
['the house of the spirits', 'Isabel Allende', 'http://images.amazon.com/images/P/0553273914.01.MZZZZZZZ.jpg']
['pride and prejudice', 'Jane Austen', 'http://images.amazon.com/images/P/055321215X.01.MZZZZZZZ.jpg']
['seabiscuit', 'LAURA HILLENBRAND', 'http://images.amazon.com/images/P/0345465083.01.MZZZZZZZ.jpg']
['notes from a small island', 'Bill Bryson', 'http://images.amazon.com/images/P/0380727501.01.MZZZZZZZ.jpg']

In [57]:
data

[['one hundred years of solitude',
  'Gabriel Garcia Marquez',
  'http://images.amazon.com/images/P/0060929790.01.MZZZZZZZ.jpg'],
 ['the house of the spirits',
  'Isabel Allende',
  'http://images.amazon.com/images/P/0553273914.01.MZZZZZZZ.jpg'],
 ['pride and prejudice',
  'Jane Austen',
  'http://images.amazon.com/images/P/055321215X.01.MZZZZZZZ.jpg'],
 ['seabiscuit',
  'LAURA HILLENBRAND',
  'http://images.amazon.com/images/P/0345465083.01.MZZZZZZZ.jpg'],
 ['notes from a small island',
  'Bill Bryson',
  'http://images.amazon.com/images/P/0380727501.01.MZZZZZZZ.jpg']]

In [58]:
def recommeder(book):

    index = np.where(pivot_df.index == book)[0][0]

    similar_books = sorted(list(enumerate(cosine_similarity_score[index])), key=lambda x:x[1], reverse=True)[1:6]
    book_names = []
    for i in similar_books:
        name = pivot_df.index[i[0]]
        book_names.append(name)
    return book_names

In [59]:
recommeder('1984')

['animal farm',
 "the handmaid's tale",
 'brave new world',
 'the vampire lestat (vampire chronicles, book ii)',
 'the hours : a novel']

In [60]:
def recommend(book_name):
    index = np.where(pivot_df.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(cosine_similarity_score[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pivot_df.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [61]:
data = recommend('1984')

In [62]:
data[0][2]

'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'

In [63]:
for i in range(len(data)):
    print(data[i][2])

http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg
http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg
http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg
http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg

In [64]:
for i in range(len(data)):
    print(" ")
    for j in range(3):
        print(data[i][j])
        # print(" ")

animal farm
George Orwell
http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg

the handmaid's tale
Margaret Atwood
http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg

brave new world
Aldous Huxley
http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg

the vampire lestat (vampire chronicles, book ii)
ANNE RICE
http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg

In [65]:
import pickle

In [66]:
pickle.dump(popular_books_df,open(r'G:\Robotronix\Projects\Book_recommender_system\popular_books_df.pkl','wb'))
pickle.dump(pivot_df,open(r'G:\Robotronix\Projects\Book_recommender_system\pivot_df.pkl','wb'))
pickle.dump(books,open(r'G:\Robotronix\Projects\Book_recommender_system\books.pkl','wb'))
pickle.dump(cosine_similarity_score,open(r'G:\Robotronix\Projects\Book_recommender_system\cosine_similarity_scores.pkl','wb'))

In [67]:
popular_books_df

,Book-Title,Book-Author,Image-URL-M,rating_count,avg_ratings
0,harry potter and the prisoner of azkaban (book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,harry potter and the goblet of fire (book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,harry potter and the sorcerer's stone (book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,harry potter and the order of the phoenix (boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,harry potter and the chamber of secrets (book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
...,...,...,...,...,...
753,vinegar hill (oprah's book club (paperback)),A. Manette Ansay,http://images.amazon.com/images/P/0380730138.0...,265,2.245283
754,whispers,BELVA PLAIN,http://images.amazon.com/images/P/0440216745.0...,286,2.199301
764,presumed innocent,Scott Turow,http://images.amazon.com/images/P/0446359866.0...,296,2.125000
771,isle of dogs,Patricia Cornwell,http://images.amazon.com/images/P/0425182908.0...,288,2.000000
777,wild animus,Rich Shapero,http://images.amazon.com/images/P/0971880107.0...,2502,1.019584

In [68]:
# search top 10 books

list(popular_books_df['Book-Title'].values)[:10]

['harry potter and the prisoner of azkaban (book 3)',
 'harry potter and the goblet of fire (book 4)',
 "harry potter and the sorcerer's stone (book 1)",
 'harry potter and the order of the phoenix (book 5)',
 'harry potter and the chamber of secrets (book 2)',
 'the hobbit : the enchanting prelude to the lord of the rings',
 'the fellowship of the ring (the lord of the rings, part 1)',
 "harry potter and the sorcerer's stone (harry potter (paperback))",
 'the two towers (the lord of the rings, part 2)',
 'to kill a mockingbird']